version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - 'dependencies'
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - '@puppetlabs/compliance'
    schedule:
      interval: daily
      time: '07:00'
  - package-ecosystem: gomod
    directory: /
    labels:
      - 'dependencies'
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - '@puppetlabs/compliance'
    schedule:
      interval: daily
      time: '07:00'
