run:
  tests: false

linters:
  enable-all: true
  disable:
    - exhaustivestruct    # deprecated
    - exhaustruct         # overly cautious
    - goimports           # clashes with gci
    - golint              # deprecated
    - ifshort             # enforces an unintuitive coding style
    - interfacer          # deprecated
    - maligned            # deprecated
    - nonamedreturns      # named returns are required to handle errors from deferred functions
    - scopelint           # deprecated
    - varnamelen          # complains about short variable names even if they are appropriate
    - wsl                 # overly opinionated about whitespacing style

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
