run:
  tests: false

linters:
  enable-all: true
  disable:
    - deadcode            # deprecated
    - exhaustive          # not practical
    - exhaustivestruct    # deprecated
    - exhaustruct         # not practical
    - golint              # deprecated
    - ifshort             # deprecated
    - interfacer          # deprecated
    - ireturn             # good principle but occasional exceptions exist
    - maligned            # deprecated
    - nolintlint          # (*) disabled until 'leading space' clash with gofmt/gofumpt formatting is resolved
    - nonamedreturns      # named returns are required to handle errors from deferred functions
    - nosnakecase         # deprecated
    - scopelint           # deprecated
    - structcheck         # deprecated
    - varcheck            # deprecated
    - varnamelen          # disallows short variable names even if they are appropriate
    - wsl                 # too aggressive

linters-settings:
  funlen:
    lines: -1
  lll:
    tab-width: 4

issues:
  exclude-rules:
    - path: ^.*main\.go$
      linters:
        - cyclop
        - forbidigo
        - funlen
        - gochecknoglobals
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
