run:
  tests: false

linters:
  enable-all: true
  disable:
    - cyclop            # better judged on a case-by-case basis
    - depguard          # we do not restrict package imports
    - exhaustruct       # mandatory initialization of all struct fields is impractical
    - funlen            # better judged on a case-by-case basis
    - gochecknoglobals  # better judged on a case-by-case basis
    - gocognit          # better judged on a case-by-case basis
    - goconst           # better judged on a case-by-case basis
    - gomnd             # better judged on a case-by-case basis
    - nestif            # better judged on a case-by-case basis
    - nonamedreturns    # named returns are required to handle errors from deferred functions
    - varnamelen        # better judged on a case-by-case basis
    - wsl               # too aggressive

    # linters disabled because they are deprecated:
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

linters-settings:
  lll:
    tab-width: 4
  tagliatelle:
    case:
      rules:
        json: snake

issues:
  exclude-rules:
    - path: cmd/
      linters:
        - cyclop
        - forbidigo
        - funlen
        - gochecknoglobals
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
