name: Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          args: "--timeout=2m --verbose"
          github-token: ${{ secrets.github_token }}
          version: v1.47.2
