name: pr-build
on: [pull_request]
jobs:
  Acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.4'
      - name: Run tests
        run: |
          make test
      - name: Run lint
        run: |
          make lint
