name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '^1.16.15'
      - name: Run unit tests
        run: |
          make test
